name: Linux-64
on:
  push:
  pull_request:
    branches:
      - main

jobs:
  testing:
    name: Ubuntu 64-bit
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        preset: [linux-x64-coverage, linux-x64-release]
    steps:
      - name: Install deps
        run: |
          sudo apt update && sudo apt install -y nasm autoconf automake libtool autoconf-archive \
            pkg-config cmake ninja-build gnome-desktop-testing libasound2-dev libpulse-dev \
            libaudio-dev libfribidi-dev libjack-dev libsndio-dev libx11-dev libxext-dev \
            libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev libxtst-dev \
            libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev \
            libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev libthai-dev libusb-1.0-0-dev \
            libpipewire-0.3-dev libwayland-dev libdecor-0-dev liburing-dev glslang-tools libvulkan-dev \
            mesa-vulkan-drivers \
            qt6-base-dev qt6-base-private-dev qt6-qpa-plugins

      - name: Checkout
        uses: actions/checkout@v5

      # Install latest CMake and Ninja.
      - uses: lukka/get-cmake@latest

      - name: Cache vcpkg
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/vcpkg_cache
          key: vcpkg-${{ matrix.preset }}-${{ hashFiles('vcpkg.json', 'vcpkg-configuration.json', 'CMakePresets.json') }}

      # Setup vcpkg: ensures vcpkg is downloaded and built.
      - name: Setup a new (or from cache) vcpkg (and does not build any package)
        uses: lukka/run-vcpkg@v11

      - name: Start virtual display
        run: |
          Xvfb :1 -screen 0 1024x768x24 &
          echo "DISPLAY=:1" >> $GITHUB_ENV

      - name: Run CMake consuming CMakePreset.json and run vcpkg to build packages
        uses: lukka/run-cmake@v10
        env:
          VCPKG_BINARY_SOURCES: clear;files,${{ github.workspace }}/vcpkg_cache,readwrite
        with:
          configurePreset: "${{ matrix.preset }}"
          buildPreset: "${{ matrix.preset }}"
          testPreset: "${{ matrix.preset }}"
      
      - name: Upload code coverage to Codecov
        if: matrix.preset == 'linux-x64-coverage'
        uses: codecov/codecov-action@v6
        with:
          files: ./coverage.info
          flags: linux-x64
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

